### PR TITLE
Fixes static translation path being used

### PR DESCRIPTION
**Pull request by kas-luthor**

### CODE REVIEW

**Comment by hackhaslam** [comment]
This wouldn't work for the bundled .app structure on macOS. I'm already working on installing translation files and loading from the installed location.

**Comment by hackhaslam** [comment]
BTW, I do realize that I broke it with my last change and I'm fixing that too.

**Comment by hackhaslam** [comment]
@kas-luthor I just pushed a commit that fixes the path to the generated .qm files. Let me know if it's still broken for you. I'm still working on actually installing the translation files.

Feel free to email me directly (at the email address in my commits) if you want to coordinate or discuss anything.

**Comment by kas-luthor** [comment]
@hackhaslam Your fix solved the problem

**Pull request closed without merging**
