### PR TITLE
Flatpak manifest

### PR DESCRIPTION
**Pull request by Murmele**
This is the first draft for a flatpak manifest
https://flatpak.org/

### CODE REVIEW

**Comment by i-need-to-tell-you-something** [comment]
Corresponding issue: #151

**Comment by Croydon** [comment]
With the official blessing from @hackhaslam this could be moved to be hosted on [Flathub](https;//flathub.org) and a connected github.com/flathub repository 

From there it would be a lot easier to discover, install and probably also to maintain

**Comment by TheEvilSkeleton** [comment]
Any update in this?

**Comment by Croydon** [comment]
Gitahead is available on Flathub 

https://flathub.org/apps/details/io.github.gitahead.GitAhead

https://github.com/flathub/io.github.gitahead.GitAhead

If @hackhaslam wants, it is possible [to request ownership of your own apps](https://github.com/flathub/flathub/wiki/App-Submission#someone-else-has-put-my-app-on-flathubwhat-do-i-do).

I think this can be closed as there is no point to maintain a second Flatpak setup here

**Comment by Murmele** [comment]
@Croydon 
Thank you for publishing. I have some questions about your? manifest (just interested):
- Why is there graphviz needed?
- Why do you copy git into the /app/bin folder?

**Comment by Croydon** [comment]
I did not do the work 

https://github.com/flathub/flathub/pull/2286

https://github.com/flathub/io.github.gitahead.GitAhead/commits/master

**Pull request closed without merging**
