### PR TITLE
Update of the Brazilian Portuguese translation.

### PR DESCRIPTION
**Pull request by gomes2191**

### CODE REVIEW

**Comment by gomes2191** [comment]
Following is the translation to Portuguese with the necessary updates please disregard the previous pulls request that were with extra file dependencies.

**Comment by hackhaslam** [comment]
Does this subsume the other two open PRs?

**Comment by hackhaslam** [comment]
Okay, I merged this one and closed the other two.

**Comment by gomes2191** [comment]
Yes, only the latter ...

**Pull request merged**
