### PR TITLE
Fix the problem of sometimes not being able stage all files.

### PR DESCRIPTION
**Pull request by Maickonn**
Fix issue #428 (sometimes not being able stage all files).

Bug:

81724291-822a5000-945a-11ea-8127-88d71ef3430f

---

Potential solution:

Untitled Project

### CODE REVIEW

**Comment by Maickonn** [comment]
> It's supposed to allow the status diff to show renames. Whether that's working or not (it sounds like you're saying it's not?) I don't know.

So @hackhaslam, with this change apparently fixed the problem.

**Comment by Maickonn** [comment]
@hackhaslam after many days testing and using this PR on many projects, I did not find any problems with this change. It's working fine.

**Comment by hackhaslam** [comment]
@Maickonn a while ago I checked in a fix for rename detection in the status diff. It wasn't working because the option to check untracked files wasn't enabled.

However, after testing it, it's apparent that rename detection never really worked correctly in the status diff. There would have to be special logic in the `Index` class for staging the rename. So I checked in the fix you proposed and removed similarity detection from the status diff.

**Comment by Maickonn** [comment]
> @Maickonn a while ago I checked in a fix for rename detection in the status diff. It wasn't working because the option to check untracked files wasn't enabled.
> 
> However, after testing it, it's apparent that rename detection never really worked correctly in the status diff. There would have to be special logic in the `Index` class for staging the rename. So I checked in the fix you proposed and removed similarity detection from the status diff.

Right! After several days using the new version with the change made, I had no more problems. I believe that the correction was very effective. Thank you.

**Pull request closed without merging**
