### PR TITLE
Adds auto-detection of provided languages

### PR DESCRIPTION
**Pull request by kas-luthor**
Via enumeration of translation files

### CODE REVIEW

**Comment by hackhaslam** [comment]
This didn't work for me in practice. I tried to add a new language by creating a new empty .ts file. I expected `lupdate` to fill in the contents of the file, but it just failed with an error.

I switched back to enumerating the expected languages and changed the `TS_FILES` variable to derive from that instead of globbing for them.

**Comment by kas-luthor** [comment]
It expects a valid translation file, not just an empty one. Copying an existing one should do the trick.
Alternatively, an empty template file could be provided.

**Comment by hackhaslam** [comment]
I think the change I made is fine. To add a new language, just add the language code to the list of languages in the cmake file.

**Comment by kas-luthor** [comment]
That's fair

**Pull request merged**
