### PR TITLE
stage/unstage/discard single lines of a hunk

### PR DESCRIPTION
**Pull request by Murmele**
Able to stage/unstage/discard single lines of a hunk.
To stage a line, 
   - click to the left of the line numbers
   - select text you would like to stage
       - and make right click and select "stage selected"
       - or press "s" to stage and "u" to unstage

For reverting press "r" on the keyboard.

Please give me feedback :)

### CODE REVIEW

**Comment by Murmele** [comment]
I added a few unit tests, but I don't understand how to run them locally. When I am building them, not executable is created

**Comment by Murmele** [comment]
Why the test step did not fail?

image

**Comment by TWille** [comment]
Perfect, if this one is merged, GitAhead can be used for a whole range of other projects aswell, writing guidelines etc. I've shared it within my network. Thx for the effort!

**Comment by hoijui** [comment]
This functionality is essential for a git commit tool. without it, one has to use an external tool (`git gui` _does_ support this, for example), which destroys the purpose of using GitAhead (as a thing to make ones life easier) in the first place. To me, this is _the_ killer feature that is missing in GitAhead. I just tested a lot of git GUI tools. because of this, GitAhead failed the minimum standard, with this, it would be on the top of the list (above `gitg` and `git-cola`).
I did this extnesive testing for a group of open source hardware developers (mostly git novices).
The good looks of GitAhead would easily make it a favorite of most of them, but I can;t recommend it without this feature.

**Comment by hoijui** [comment]
thank you @Murmele ! :-)
ride on!

**Comment by Murmele** [comment]
Thank you :)
hackhaslam will review it when he finds time for it

**Comment by Murmele** [comment]
I'm not able to compile for windows. Is there anybody wo can do that?

**Comment by Murmele** [comment]
@hackhaslam Do you plan to review it?

**Comment by hackhaslam** [comment]
@Murmele I don't think I can review this. It changes a *bunch* of things unrelated to staging/unstaging lines. It would be much easier to review PRs that change one thing at a time.

However, I must say that my time is *extremely* constrained at the moment. I hope to be carve out some time to review the backlog of patches soon, but I don't know when that will be. I'm sorry.

**Comment by Murmele** [comment]
Ok I will try to make smaller patches so the review gets faster

**Comment by farfromrefug** [comment]
@Murmele you are going to create a new PR for this? This would make me switch to GitAhead!

**Comment by Murmele** [comment]
@farfromrefug 
I don't think so. The problem is at the beginning i vleaned everything up and move all classes to its own file and therefore there are a lot of changes and it is hard to review. I have my own branch (Productive_New) where all my implementations are included. I'm using this one.

**Comment by farfromrefug** [comment]
@Murmele @hackhaslam Does that mean you are diverging? @hackhaslam could look at merging the refactoring of classes?
Seems really to bad for your repos to diverge ....

**Comment by Murmele** [comment]
@farfromrefug No I have my branch, but I don't have time to develop for GitAhead. If more developers will be found maybe in the future it gets merged. At the moment almost nobody is working on this project

**Comment by farfromrefug** [comment]
@Murmele I totally understand . I won't to say I ll.join but tbh I don't thinkni have any time left. 
It is quite sad as it is the most advanced oss git GUI around. I really love it. Hope it is going to survive !

**Comment by Murmele** [comment]
Yes I hope too. Yes indeed it is one of the most advamced guis under linux which is open source.

**Comment by timmwille** [comment]
so best would be to use: Productive_New branch?

**Comment by Murmele** [comment]
@timmwille 
We created a fork: https://flathub.org/apps/details/com.github.Murmele.Gittyup
https://github.com/Murmele/Gittyup
It is implemented there

**Pull request closed without merging**
