### PR TITLE
Add menu options and hotkeys for staging and unstaging

### PR DESCRIPTION
**Pull request by kas-luthor**
Implements #227
Fix menu "Repository" not being updated on switching diffs / commits (resulted in menu action "Commit" being available when viewing a commit diff)

### CODE REVIEW

**Comment by hackhaslam** [comment]
There's a slight conflict between the diff view editor's built-in text size +/- shortcut, but I went ahead and merged this anyway. Those shortcuts aren't too useful and it's probably better for this.

**Comment by kas-luthor** [comment]
> There's a slight conflict between the diff view editor's built-in text size +/- shortcut, [...]

Oh yeah, I haven't tested it with the diff editor open. This could result in the text resizing when the user double-presses the shortcut since the menu entry gets disabled after the first press.
Should we look into disabling the standard zooming hotkeys or change the hotkeys to something different?

**Comment by hackhaslam** [comment]
I just removed editor default shortcuts for zoom in/out.

**Comment by robitalec** [comment]
@hackhaslam - is there a menu setting somewhere for globally zooming in/zooming out? 
Noticing on an external monitor, the display can be a bit challenging to read. 

(Let me know if you'd prefer me to open a fresh issue)

Thanks.

**Pull request merged**
