### PR TITLE
Add a compact mode for the diff view

### LINKED ISSUE #347: Too Much File Preview Spacing
Linux v2.6.0

There is an awful lot of wasted space here between the files, wouldn't you agree?

Untitled

### PR DESCRIPTION
**Pull request by kas-luthor**
Fixes #347

### CODE REVIEW

**Comment by PoLaKoSz** [comment]
Is there any chance that this PR will be merged into `master`?

**Comment by hackhaslam** [comment]
I'm not sure. I'm not really interested in adding options to tweak spacing. I'll have to think about it.

**Comment by Murmele** [comment]
Maybe removing the space between the FileWidget Header and the HunkWidget? So it is more clear that the are together

**Comment by hackhaslam** [comment]
I've changed the layout so that there's no spacing between the file header and its hunks. There's also less space around the widgets.

**Comment by Murmele** [comment]
Looks great. Thank you
image

**Pull request closed without merging**
