### PR TITLE
Add spell check and line length check for commit message editor

### PR DESCRIPTION
**Pull request by stefanknotzer**
New submodule: dep/hunspell from https://github.com/hunspell/hunspell
Dictionary folder: Resources/dictionaries
Dictionary source: https://cgit.freedesktop.org/libreoffice/dictionaries/tree
A user dictionary is created in the folder of the GitAhead global settings named 'user.dic'.
Settings for spell check language and line length are stored as global settings.

Dictionary chooser:
dictionaries

Spell check suggestions (replaced standard context menu):
spell_check

Context menu for line length checker:
context_button

Replaced context menu on subject line:
subject_line_check
The blank line between subject and body is enabled: a word wrap is not possible, therefore truncate is the only choice.

Replaced context menu an body line:
body_line_check
Choose to insert word wrap for the selected line or all lines.

Every change to the commit editor is done by `QTextCursor`, so undo and redo are available.
The available dictionaries are scanned once on startup. To install a new dictionary the app has to be restarted.
I added the dictionaries according to the available translations and to my surprise they compress very well. The install package grew by about 2 MB. The colors are stolen from `Theme::Diff::`.

### CODE REVIEW

**Comment by stefanknotzer** [comment]
Solves #10 and #478

**Comment by farfromrefug** [comment]
@hackhaslam are you going to merge all @stefanknotzer PRs? They are pretty amazing!

**Comment by hackhaslam** [comment]
@farfromrefug I'm going to review them when I am able.

**Comment by hackhaslam** [comment]
Initially it looks pretty good. The squiggle style is somehow messed up on macOS:

Screen Shot 2020-11-01 at 6 02 04 PM

Screen Shot 2020-11-01 at 6 05 43 PM

It's almost not visible. It looks like maybe it's clipped at the bottom? I can try to investigate.

The dictionary button also doesn't look great on macOS. Personally, I don't even think it needs to be its own interface element. It could just be a preference in the preferences panel that defaults to the user's language. Or if you think the user might want to change it frequently, it could just be another section in the gear menu.

Also, I don't immediately see the line limit stuff. Is there something special that I need to do? I haven't looked closely at the implementation.

**Comment by stefanknotzer** [comment]
@hackhaslam 
Please have a look at the new gear button (top right of the commit message editor header). There you can enable the line limits for subject and body text.

The spellcheck underline looks awful on macOS. Could this be a macOS / font / `QTextEdit` issue? I do not see this issue on Linux and Windows. I hope you find some time to investigate.

I need your suggestions:
Move the new gear button (line limit stuff) and the spell checker language setup to the context menu of the `QTextEdit`?
Just add the spell checker language setup to the gear button?
Add limit and spell checker language settings to `SettingsDialog` and `ConfigDialog` (maybe to 'General' panel)?
Trash the line limit values 'used'/'limit' display (leave the commit editor header unchanged)?

**Comment by hackhaslam** [comment]
Oh, right. I can see those options in the gear button menu now.

All of the QTextCharFormat underline styles look essentially broken on macOS. I think it might not be drawing correctly with the screen scale factor greater than one or something similar. This isn't such a big deal that it would have to block the feature going in.

Can you split this into two separate PRs, one for each of the features? I think that the spell check part looks pretty good to go. I would like to see the options for choosing the dictionary in the new gear button menu instead of its own button. I think it should be enabled by default with the default dictionary based on the user's language.

Also, please make sure that the code style is consistent with the rest of the app. Use Qt-style naming conventions with lower camel case names and avoid including `get` in the name of accessors, etc. Break lines at 80 columns.

**Comment by stefanknotzer** [comment]
See pull request #524

**Pull request closed without merging**
